/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wub.struts.form;

import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 12-10-2007
 * 
 * XDoclet definition:
 * @struts.form name="adminListForm"
 */
public class AdminListForm extends ActionForm {

	
	private List adminlist;
	
	
	/**
	 * Konstruktor
	 */
	public AdminListForm() {
		adminlist = new ArrayList();
	}
	
	
	public void setAdminlist(List adminlist) {
		this.adminlist = adminlist;
	}
	
	
	public List getAdminlist() {
		return adminlist;
	}
	
	

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {

		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		adminlist = new ArrayList();
	}
}