/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wub.struts.form;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 02-04-2008
 * 
 * XDoclet definition:
 * @struts.form name="appraisalCustomListForm"
 */
public class AppraisalClassForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** subjectId property */
	private Integer subjectId;

	/** appraisalId property */
	private Integer appraisalId;
	
	/** classId property */
	private Integer classId;

	/** adminId property */
	private Integer adminId;

	/** subjectYear property */
	private String subjectYear;

	/** endDate property */
	private String endDate;
	
	/** startDate property */
	private String startDate;

	/** name property */
	private String name;
	
	/** reuse property */
	private Boolean reuse;
	
	/** infoMessage property */
	private String infoMessage;
	
	
	
	// ----- Listen -----
	
	private List appraisalBasicList;
	private List teacherList;
	private List subjectList;
	private List studentList;
	
	

	// ----- Standardmethoden -------

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	
	// ----- Getter und Setter
	
	/** 
	 * Returns the subjectId.
	 * @return Integer
	 */
	public Integer getSubjectId() {
		return subjectId;
	}

	/** 
	 * Set the subjectId.
	 * @param subjectId The subjectId to set
	 */
	public void setSubjectId(Integer subjectId) {
		this.subjectId = subjectId;
	}

	
	/** 
	 * Returns the appraisalId.
	 * @return Integer
	 */
	public Integer getAppraisalId() {
		return appraisalId;
	}

	/** 
	 * Set the appraisalId.
	 * @param appraisalId The appraisalId to set
	 */
	public void setAppraisalId(Integer appraisalId) {
		this.appraisalId = appraisalId;
	}

	/** 
	 * Returns the classId.
	 * @return Integer
	 */
	public Integer getClassId() {
		return classId;
	}

	/** 
	 * Set the classId.
	 * @param classId The classId to set
	 */
	public void setClassId(Integer classId) {
		this.classId = classId;
	}

	/** 
	 * Returns the adminId.
	 * @return Integer
	 */
	public Integer getAdminId() {
		return adminId;
	}

	/** 
	 * Set the adminId.
	 * @param adminId The adminId to set
	 */
	public void setAdminId(Integer adminId) {
		this.adminId = adminId;
	}

	/** 
	 * Returns the subjectYear.
	 * @return String
	 */
	public String getSubjectYear() {
		return subjectYear;
	}

	/** 
	 * Set the subjectYear.
	 * @param subjectYear The subjectYear to set
	 */
	public void setSubjectYear(String subjectYear) {
		this.subjectYear = subjectYear;
	}

	/** 
	 * Returns the endDate.
	 * @return String
	 */
	public String getEndDate() {
		return endDate;
	}

	/** 
	 * Set the endDate.
	 * @param endDate The endDate to set
	 */
	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	/** 
	 * Returns the name.
	 * @return String
	 */
	public String getName() {
		return name;
	}

	/** 
	 * Set the name.
	 * @param name The name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	
	public String getStartDate() {
		return startDate;
	}

	
	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}

	public Boolean getReuse() {
		return reuse;
	}

	public void setReuse(Boolean reuse) {
		this.reuse = reuse;
	}

	public String getInfoMessage() {
		return infoMessage;
	}

	public void setInfoMessage(String infoMessage) {
		this.infoMessage = infoMessage;
	}

	public List getAppraisalBasicList() {
		return appraisalBasicList;
	}

	public void setAppraisalBasicList(List appraisalBasicList) {
		this.appraisalBasicList = appraisalBasicList;
	}

	public List getTeacherList() {
		return teacherList;
	}

	public void setTeacherList(List teacherList) {
		this.teacherList = teacherList;
	}

	public List getSubjectList() {
		return subjectList;
	}

	public void setSubjectList(List subjectList) {
		this.subjectList = subjectList;
	}

	public List getStudentList() {
		return studentList;
	}

	public void setStudentList(List studentList) {
		this.studentList = studentList;
	}
	
	
	// ------ Getter und Setter für Listen --------
	
    public StudentForm getStudentForm(int index)
    {
        // make sure that orderList is not null
        if(this.studentList == null)
        {
            this.studentList = new ArrayList();
        }
 
        // indexes do not come in order, populate empty spots
        while(index >= this.studentList.size())
        {
            this.studentList.add(new StudentForm());
        }
 
        // return the requested item
        return (StudentForm)studentList.get(index);
    }	
	
	
}