/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wub.struts.form;

import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;


/**
 * Repräsentiert eine Beurteilung, welche von einem Benutzer
 * ausgefüllt werden kann.
 * @author patric
 *
 */
@SuppressWarnings("unchecked")
public class AppraisalForm extends ActionForm {

	
	private static final long serialVersionUID = 4492479116875641023L;
	private Integer voteStyleId; // zum steuern wieviele Antwortmöglichkeiten es gibt
	private Integer statusId; // für die Verknüpfung mit der Beurteilung etc
	private String description; // der Klassen-Name
	private String teacher;
	private String subject;
	private String subjectYear;
	private String startDate;
	private String endDate;
	private List voteElementList; // enthält text, textid, vote, comment etc.
	
	
	// --- KONSTRUKTOREN ---
	
	/**
	 * Standard Konstruktor
	 */
	public AppraisalForm() {
		this.voteElementList = new ArrayList();
	}
	
	
	// --- GETTER UND SETTER ---
	

	public Integer getVoteStyleId() {
		return voteStyleId;
	}

	public void setVoteStyleId(Integer voteStyleId) {
		this.voteStyleId = voteStyleId;
	}

	public Integer getStatusId() {
		return statusId;
	}

	public void setStatusId(Integer statusId) {
		this.statusId = statusId;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getTeacher() {
		return teacher;
	}

	public void setTeacher(String teacher) {
		this.teacher = teacher;
	}

	public String getSubject() {
		return subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public String getStartDate() {
		return startDate;
	}

	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}

	public String getEndDate() {
		return endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	public String getSubjectYear() {
		return subjectYear;
	}

	public void setSubjectYear(String subjectYear) {
		this.subjectYear = subjectYear;
	}

	public List getVoteElementList() {
		return voteElementList;
	}

	public void setVoteElementList(List voteElementList) {
		this.voteElementList = voteElementList;
	}
	
	
	// --- SPEZIAL GETTER FUER LISTEN ELEMENT
	
    public AppraisalVoteElementForm getAppraisalVoteElementForm(int index)
    {
        // make sure that orderList is not null
        if(this.voteElementList == null)
        {
            this.voteElementList = new ArrayList();
        }
 
        // indexes do not come in order, populate empty spots
        while(index >= this.voteElementList.size())
        {
            this.voteElementList.add(new AppraisalVoteElementForm());
        }
 
        // return the requested item
        return (AppraisalVoteElementForm)voteElementList.get(index);
    }
	
	
	// --- STANDARD METHODEN VON STRUTS ---
	
	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		
		/* Zu jedem Text muss eine Bewertung abgegeben worden sein,
		 * Kommentare sind zwar erwünscht jedoch nicht Pflicht.
		 */
		ActionErrors errors = null;
		
		for (Object voteElementObj : voteElementList) {
			AppraisalVoteElementForm voteElement =
				(AppraisalVoteElementForm)voteElementObj;
			if (voteElement.getVote() == null) {
				// Eine Bewertung fehlt:
				if (errors == null) {
					errors = new ActionErrors();
				}
				errors.add("vote", new ActionMessage("error.user.appraisal.vote.missing"));
				break;
			}
		}
		
		return errors;
	}

	
	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
	
	
}