/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wub.struts.form;

import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/**
 * MyEclipse Struts Creation date: 01-17-2008
 * 
 * XDoclet definition:
 * 
 * @struts.form name="appraisalCoreBasicEditFormForm"
 */
public class AppraisalCoreBasicEditForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** locked property */
	private Integer locked;

	/** appraisalId property */
	private Integer appraisalId;

	/** voteStyle property */
	private Integer voteStyle;

	/** name property */
	private String name;
	
	
	private List appraisalConfigs;
	
	
	
//	public AppraisalCoreBasicEditForm() {
//		appraisalConfigs = new ArrayList();
//	}
	
	

	/*
	 * Generated Methods
	 */

	/**
	 * Method validate
	 * 
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/**
	 * Method reset
	 * 
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	
	
	
	/**
	 * Returns the locked.
	 * 
	 * @return Integer
	 */
	public Integer getLocked() {
		return locked;
	}

	/**
	 * Set the locked.
	 * 
	 * @param locked
	 *            The locked to set
	 */
	public void setLocked(Integer locked) {
		this.locked = locked;
	}

	/**
	 * Returns the appraisalId.
	 * 
	 * @return Integer
	 */
	public Integer getAppraisalId() {
		return appraisalId;
	}

	/**
	 * Set the appraisalId.
	 * 
	 * @param appraisalId
	 *            The appraisalId to set
	 */
	public void setAppraisalId(Integer appraisalId) {
		this.appraisalId = appraisalId;
	}

	/**
	 * Returns the voteStyle.
	 * 
	 * @return Integer
	 */
	public Integer getVoteStyle() {
		return voteStyle;
	}

	/**
	 * Set the voteStyle.
	 * 
	 * @param voteStyle
	 *            The voteStyle to set
	 */
	public void setVoteStyle(Integer voteStyle) {
		this.voteStyle = voteStyle;
	}

	/**
	 * Returns the name.
	 * 
	 * @return String
	 */
	public String getName() {
		return name;
	}

	/**
	 * Set the name.
	 * 
	 * @param name
	 *            The name to set
	 */
	public void setName(String name) {
		this.name = name;
	}
	
	/**
	 * Returns the appraisalConfigs.
	 * 
	 * @return appraisalConfigs
	 */
	public List getAppraisalConfigs() {
		return this.appraisalConfigs;
	}
	
	
	public void setAppraisalConfigs(List list) {
		this.appraisalConfigs = list;
	}


    public AppraisalConfigEditForm getAppraisalConfigEditForm(int index)
    {
        // make sure that orderList is not null
        if(this.appraisalConfigs == null)
        {
            this.appraisalConfigs = new ArrayList();
        }
 
        // indexes do not come in order, populate empty spots
        while(index >= this.appraisalConfigs.size())
        {
            this.appraisalConfigs.add(new AppraisalConfigEditForm());
        }
 
        // return the requested item
        return (AppraisalConfigEditForm)appraisalConfigs.get(index);
    }
	

}