/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wub.struts.form;

import java.text.DecimalFormat;
import java.util.List;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 02-26-2008
 * 
 * XDoclet definition:
 * @struts.form name="appraisalStatisicVoteElementForm"
 */
public class AppraisalStatisicVoteElementForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** vote property */
	private Double vote;

	/** text property */
	private String text;
	
	/** text commentList */
	private List commentList;



	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the vote.
	 * @return Double
	 */
	public Double getVote() {
		return vote;
	}
	
	
	/**
	 * Gibt die Bewertung formatiert zurück
	 * @return
	 */
	public String getVoteString() {
		DecimalFormat df = new DecimalFormat( "###,##0.00" ); 
		return df.format(this.vote); 
	}

	/** 
	 * Set the vote.
	 * @param vote The vote to set
	 */
	public void setVote(Double vote) {
		this.vote = vote;
	}

	/** 
	 * Returns the text.
	 * @return String
	 */
	public String getText() {
		return text;
	}

	/** 
	 * Set the text.
	 * @param text The text to set
	 */
	public void setText(String text) {
		this.text = text;
	}

	
	
	public List getCommentList() {
		return commentList;
	}

	public void setCommentList(List commentList) {
		this.commentList = commentList;
	}
	
	
	

	
}