/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wub.struts.form;

import java.util.List;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 02-26-2008
 * 
 * XDoclet definition:
 * @struts.form name="appraisalStatisticForm"
 */
@SuppressWarnings("unchecked")
public class AppraisalStatisticForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** startDate property */
	private String startDate;

	/** description property */
	private String description;

	/** subjectYear property */
	private String subjectYear;

	/** endDate property */
	private String endDate;

	/** subject property */
	private String subject;

	/** teacher property */
	private String teacher;

	/** voteElementList property */
	private List voteElementList;
	
	/** voteCount property */
	private Integer voteCount;
	
	/** maxVote property */
	private Integer maxVote;
	

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the startDate.
	 * @return String
	 */
	public String getStartDate() {
		return startDate;
	}

	/** 
	 * Set the startDate.
	 * @param startDate The startDate to set
	 */
	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}

	/** 
	 * Returns the description.
	 * @return String
	 */
	public String getDescription() {
		return description;
	}

	/** 
	 * Set the description.
	 * @param description The description to set
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/** 
	 * Returns the subjectYear.
	 * @return String
	 */
	public String getSubjectYear() {
		return subjectYear;
	}

	/** 
	 * Set the subjectYear.
	 * @param subjectYear The subjectYear to set
	 */
	public void setSubjectYear(String subjectYear) {
		this.subjectYear = subjectYear;
	}

	/** 
	 * Returns the endDate.
	 * @return String
	 */
	public String getEndDate() {
		return endDate;
	}

	/** 
	 * Set the endDate.
	 * @param endDate The endDate to set
	 */
	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	/** 
	 * Returns the subject.
	 * @return String
	 */
	public String getSubject() {
		return subject;
	}

	/** 
	 * Set the subject.
	 * @param subject The subject to set
	 */
	public void setSubject(String subject) {
		this.subject = subject;
	}

	/** 
	 * Returns the teacher.
	 * @return String
	 */
	public String getTeacher() {
		return teacher;
	}

	/** 
	 * Set the teacher.
	 * @param teacher The teacher to set
	 */
	public void setTeacher(String teacher) {
		this.teacher = teacher;
	}

	public List getVoteElementList() {
		return voteElementList;
	}

	public void setVoteElementList(List voteElementList) {
		this.voteElementList = voteElementList;
	}

	public Integer getVoteCount() {
		return voteCount;
	}

	public void setVoteCount(Integer voteCount) {
		this.voteCount = voteCount;
	}

	public Integer getMaxVote() {
		return maxVote;
	}

	public void setMaxVote(Integer maxVote) {
		this.maxVote = maxVote;
	}


}