/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wub.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 02-19-2008
 * 
 * XDoclet definition:
 * @struts.form name="appraisalVoteElementForm"
 */
public class AppraisalVoteElementForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** vote property */
	private Integer vote;

	/** title property */
	private String title;
	
	/** text property */
	private String text;

	/** comment property */
	private String comment;

	/** textId property */
	private Integer textId;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the vote.
	 * @return Integer
	 */
	public Integer getVote() {
		return vote;
	}

	/** 
	 * Set the vote.
	 * @param vote The vote to set
	 */
	public void setVote(Integer vote) {
		this.vote = vote;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	/** 
	 * Returns the text.
	 * @return String
	 */
	public String getText() {
		return text;
	}

	/** 
	 * Set the text.
	 * @param text The text to set
	 */
	public void setText(String text) {
		this.text = text;
	}

	/** 
	 * Returns the comment.
	 * @return String
	 */
	public String getComment() {
		return comment;
	}

	/** 
	 * Set the comment.
	 * @param comment The comment to set
	 */
	public void setComment(String comment) {
		this.comment = comment;
	}

	/** 
	 * Returns the textId.
	 * @return Integer
	 */
	public Integer getTextId() {
		return textId;
	}

	/** 
	 * Set the textId.
	 * @param textId The textId to set
	 */
	public void setTextId(Integer textId) {
		this.textId = textId;
	}
}