/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wub.struts.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

/** 
 * MyEclipse Struts
 * Creation date: 12-02-2007
 * 
 * XDoclet definition:
 * @struts.form name="changePasswordForm"
 */
@SuppressWarnings("serial")
public class ChangePasswordForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** newPasswordCheck property */
	private String newPasswordCheck;

	/** oldPassword property */
	private String oldPassword;

	/** newPassword property */
	private String newPassword;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		ActionErrors errors = null;
		if (oldPassword == null || oldPassword.length() < 1) {
			if (errors == null) {
				errors = new ActionErrors();
			}
			errors.add("oldPassword", new ActionMessage("error.admin.changepassword.oldpasswordmissing"));
		}
		if (newPassword == null || newPassword.length() < 1) {
			if (errors == null) {
				errors = new ActionErrors();
			}
			errors.add("newPassword", new ActionMessage("error.admin.changepassword.newpasswordmissing"));
		}
		if (newPasswordCheck == null || newPasswordCheck.length() < 1) {
			if (errors == null) {
				errors = new ActionErrors();
			}
			errors.add("newPasswordCheck", new ActionMessage("error.admin.changepassword.newpasswordcheckmissing"));
		}
		if (newPassword != null && newPasswordCheck != null && !newPassword.equals(newPasswordCheck)) {
			if (errors == null) {
				errors = new ActionErrors();
			}
			errors.add("newPasswordMatch", new ActionMessage("error.admin.changepassword.passwordmatch"));
		}
		

		return errors;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the newPasswordCheck.
	 * @return String
	 */
	public String getNewPasswordCheck() {
		return newPasswordCheck;
	}

	/** 
	 * Set the newPasswordCheck.
	 * @param newPasswordCheck The newPasswordCheck to set
	 */
	public void setNewPasswordCheck(String newPasswordCheck) {
		this.newPasswordCheck = newPasswordCheck;
	}

	/** 
	 * Returns the oldPassword.
	 * @return String
	 */
	public String getOldPassword() {
		return oldPassword;
	}

	/** 
	 * Set the oldPassword.
	 * @param oldPassword The oldPassword to set
	 */
	public void setOldPassword(String oldPassword) {
		this.oldPassword = oldPassword;
	}

	/** 
	 * Returns the newPassword.
	 * @return String
	 */
	public String getNewPassword() {
		return newPassword;
	}

	/** 
	 * Set the newPassword.
	 * @param newPassword The newPassword to set
	 */
	public void setNewPassword(String newPassword) {
		this.newPassword = newPassword;
	}
}