/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wub.struts.form;

import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 02-16-2008
 * 
 * XDoclet definition:
 * @struts.form name="classSendListForm"
 */
public class ClassSendListForm extends ActionForm {

	
	private String message;
	private boolean error;
	private String name;
	private String teacher;
	private String subject;
	private String start;
	private String end;
	private boolean sent;
	private boolean sendToAll;
	private List userList;

	
	
	/**
	 * Konstruktor
	 */
	public ClassSendListForm() {
		userList = new ArrayList();
	}
	
	
	// Getters und Setters
	
	
	public String getTeacher() {
		return teacher;
	}


	public void setTeacher(String teacher) {
		this.teacher = teacher;
	}


	public String getSubject() {
		return subject;
	}


	public void setSubject(String subject) {
		this.subject = subject;
	}


	public String getStart() {
		return start;
	}


	public void setStart(String start) {
		this.start = start;
	}


	public String getEnd() {
		return end;
	}


	public void setEnd(String end) {
		this.end = end;
	}


	public boolean getSent() {
		return sent;
	}


	public void setSent(boolean sent) {
		this.sent = sent;
	}


	/**
	 * Speichere Benutzerliste
	 * @param userList
	 */
	public void setUserList(List userList) {
		this.userList = userList;
	}
	
	
	/**
	 * Hole benutzerliste
	 * @return
	 */
	public List getUserList() {
		return userList;
	}
	
	

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}


	public String getName() {
		return name;
	}


	public void setName(String name) {
		this.name = name;
	}


	public String getMessage() {
		return message;
	}


	public void setMessage(String message) {
		this.message = message;
	}


	public boolean getError() {
		return error;
	}


	public void setError(boolean error) {
		this.error = error;
	}
	
	public boolean getSendToAll() {
		return sendToAll;
	}


	public void setSendToAll(boolean sendToAll) {
		this.sendToAll = sendToAll;
	}	
	
	// Spezial "Accessor" für Listen-Element
    public ClassSendForm getClassSendForm(int index)
    {
        // make sure that orderList is not null
        if(this.userList == null)
        {
            this.userList = new ArrayList();
        }
 
        // indexes do not come in order, populate empty spots
        while(index >= this.userList.size())
        {
            this.userList.add(new ClassSendForm());
        }
 
        // return the requested item
        return (ClassSendForm)userList.get(index);
    }



	
}