/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wub.struts.form;

import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import com.wub.db.Settings;

/** 
 * MyEclipse Struts
 * Creation date: 02-14-2008
 * 
 * XDoclet definition:
 * @struts.form name="settingListForm"
 */
public class SettingListForm extends ActionForm {
	
	
	/** settingList property */
	private List settingList;
	
	
	/**
	 * Liefert die Liste mit Settings zurück
	 * @param classList
	 */
	public void setSettingList(List settingList) {
		this.settingList = settingList;
	}
	
	
	/**
	 * Speichert eine Liste mit Settings
	 * @return
	 */
	public List getSettingList() {
		return this.settingList;
	}
	
	
	/**
	 * Einzelnes Setting auslesen
	 * @param index
	 * @return
	 */
    public Settings getSettings(int index)
    {
        // make sure that orderList is not null
        if(this.settingList == null)
        {
            this.settingList = new ArrayList();
        }
 
        // indexes do not come in order, populate empty spots
        while(index >= this.settingList.size())
        {
            this.settingList.add(new Settings());
        }
 
        // return the requested item
        return (Settings)settingList.get(index);
    }
	
	
	
	/**
	 * Konstruktor
	 */
	public SettingListForm() {
		this.settingList = new ArrayList();
	}
	
	

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
}