/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wub.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 02-24-2008
 * 
 * XDoclet definition:
 * @struts.form name="statisticSelectionForm"
 */
public class StatisticSelectionForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** subjectId property */
	private Integer subjectId;

	/** classId property */
	private Integer classId;

	/** teacherId property */
	private Integer teacherId;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the subjectId.
	 * @return Integer
	 */
	public Integer getSubjectId() {
		return subjectId;
	}

	/** 
	 * Set the subjectId.
	 * @param subjectId The subjectId to set
	 */
	public void setSubjectId(Integer subjectId) {
		this.subjectId = subjectId;
	}

	/** 
	 * Returns the classId.
	 * @return Integer
	 */
	public Integer getClassId() {
		return classId;
	}

	/** 
	 * Set the classId.
	 * @param classId The classId to set
	 */
	public void setClassId(Integer classId) {
		this.classId = classId;
	}

	/** 
	 * Returns the teacherId.
	 * @return Integer
	 */
	public Integer getTeacherId() {
		return teacherId;
	}

	/** 
	 * Set the teacherId.
	 * @param teacherId The teacherId to set
	 */
	public void setTeacherId(Integer teacherId) {
		this.teacherId = teacherId;
	}
}