/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wub.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 01-06-2008
 * 
 * XDoclet definition:
 * @struts.form name="textElementEditForm"
 */
public class TextElementEditForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** text property */
	private String text;

	/** title property */
	private String title;

	/** textId property */
	private Integer textId;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the text.
	 * @return String
	 */
	public String getText() {
		return text;
	}

	/** 
	 * Set the text.
	 * @param text The text to set
	 */
	public void setText(String text) {
		this.text = text;
	}

	/** 
	 * Returns the title.
	 * @return String
	 */
	public String getTitle() {
		return title;
	}

	/** 
	 * Set the title.
	 * @param title The title to set
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/** 
	 * Returns the textId.
	 * @return Integer
	 */
	public Integer getTextId() {
		return textId;
	}

	/** 
	 * Set the textId.
	 * @param textId The textId to set
	 */
	public void setTextId(Integer textId) {
		this.textId = textId;
	}
}