/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wub.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

/** 
 * MyEclipse Struts
 * Creation date: 02-18-2008
 * 
 * XDoclet definition:
 * @struts.form name="userLogonForm"
 */
public class UserLogonForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** useremail property */
	private String useremail;

	/** token property */
	private String token;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		
		ActionErrors errors = null;
		
		if (this.useremail == null || this.useremail.length() < 1) {
			if (errors == null) {
				errors = new ActionErrors();
			}
			errors.add("oldPassword", new ActionMessage("error.user.login.missingemail"));
		}
		if (this.token == null || this.token.length() < 1) {
			if (errors == null) {
				errors = new ActionErrors();
			}
			errors.add("newPassword", new ActionMessage("error.user.login.missingtoken"));
		}
		
		return errors;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the useremail.
	 * @return String
	 */
	public String getUseremail() {
		return useremail;
	}

	/** 
	 * Set the useremail.
	 * @param username The useremail to set
	 */
	public void setUseremail(String useremail) {
		this.useremail = useremail;
	}

	/** 
	 * Returns the token.
	 * @return String
	 */
	public String getToken() {
		return token;
	}

	/** 
	 * Set the token.
	 * @param token The token to set
	 */
	public void setToken(String token) {
		this.token = token;
	}
}