/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wub.struts.action;

import java.util.Collections;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.wub.db.Administrators;
import com.wub.handlers.AdminUserHandler;
import com.wub.handlers.RoleHandler;
import com.wub.handlers.RoleHandler.AdminRole;
import com.wub.struts.form.AdminListForm;

/** 
 * MyEclipse Struts
 * Creation date: 12-10-2007
 * 
 * XDoclet definition:
 * @struts.action path="/adminList" name="adminListForm" input="/adminmanager.jsp" scope="request" validate="true"
 */
public class AdminListAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		if(request.getSession().getAttribute(AdminUserHandler.ADMINDATA) == null) {
			// nicht eingeloggt -> zu startseite leiten
			return mapping.findForward("start");
		}
		else {
			// Berechtigung prüfen
			RoleHandler roleHandler = RoleHandler.getInstance();
			Administrators admin = (Administrators)request.getSession().getAttribute(AdminUserHandler.ADMINDATA);
			
			if (roleHandler.checkAccess(admin.getAdminId(), AdminRole.USERMANAGER)) {
				// Zutritt erlaubt
				// ------------------------
				// AdminManager vorbereiten
				AdminListForm adminListForm;
				if (form == null) {
					adminListForm = new AdminListForm();
				}
				else {
					adminListForm = (AdminListForm)form;
				}
				
				// abfüllen der Admin-Liste
				AdminUserHandler adminUserHandler =AdminUserHandler.getInstance();
				List adminList = adminUserHandler.getAdministrators();
				
				// Liste sortieren
				Collections.sort(adminList);
				
				adminListForm.setAdminlist(adminList);
				
				// wir müssen die Liste im Scope speichern, damit sie auf der Seite verfügbar ist
				request.setAttribute(AdminUserHandler.ADMINLIST, adminListForm);
				
				return mapping.findForward("showList");
			} else {
				// Kein Zutritt
				return mapping.findForward("adminPermissionMissing");
			}
		}
		
		
		
	}
}