/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wub.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.wub.handlers.AdminUserHandler;
import com.wub.handlers.AppraisalHandler;
import com.wub.struts.form.AppraisalClassForm;
import com.wub.struts.form.AppraisalClassListForm;
import com.wub.struts.form.AppraisalCoreBasicListForm;

/** 
 * MyEclipse Struts
 * Creation date: 02-03-2008
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class AppraisalClassListAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		
		AppraisalClassListForm appraisalClassListForm = (AppraisalClassListForm) form;

		
		if(request.getSession().getAttribute(AdminUserHandler.ADMINDATA) != null) {
			
			// Liste der "Klassen" vorbereiten
			if (appraisalClassListForm == null) {
				appraisalClassListForm = new AppraisalClassListForm();
			}
			
			// abfüllen der List-Elemente
			AppraisalHandler appraisalHandler = AppraisalHandler.getInstance();
			List classList = appraisalHandler.getClassList();
		
			appraisalClassListForm.setClassList(classList);
			
			// wir müssen die Liste im Scope speichern, damit sie auf der Seite verfügbar ist
			request.setAttribute(AppraisalHandler.APPRAISALCLASSLIST, appraisalClassListForm);
			
			return mapping.findForward("showList");
		}
		
		// nicht eingeloggt -> zu startseite leiten
		return mapping.findForward("start");
	}
}