/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wub.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.wub.db.Administrators;
import com.wub.handlers.AdminUserHandler;
import com.wub.struts.form.LogonForm;

/** 
 * MyEclipse Struts
 * Creation date: 11-29-2007
 * 
 * XDoclet definition:
 * @struts.action path="/checkAdminLogon" name="logonForm" input="page.adminlogon" scope="request" validate="true"
 */
public class CheckAdminLogonAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		
		// prüfen ob user bereits eingeloggt war
		HttpSession session = request.getSession();
		
		if (session != null) {
			Administrators adminEntry = (Administrators)session.getAttribute(AdminUserHandler.ADMINDATA);
			
			if (adminEntry != null) {
				// direkt weiterleiten
				return mapping.findForward("success");
			}
			else
			{
				// daten aus Formular überprüfen
				LogonForm logonForm = (LogonForm) form;
				
				if (!(logonForm.getUsername() == null || logonForm.getUsername().equals("") || logonForm.getPassword() == null)) {
					// Formular wurde ausgefüllt
					
					// get Handler for handling administrators
					AdminUserHandler adminHandler = AdminUserHandler.getInstance();
					
					// get entry according to parameters of form
					Administrators newAminEntry = adminHandler.checkLogin(logonForm.getUsername(), logonForm.getPassword());
					
					// überprüfen ob resultat vorhanden
					if (newAminEntry != null)
					{
						// login OK
						session.setAttribute(AdminUserHandler.ADMINDATA, newAminEntry);
						
						return mapping.findForward("success");
					}
				}
			}
		}
		
		// kein gültiger Login
		return mapping.findForward("logonFailed");
	}
}