/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wub.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.wub.handlers.AppraisalHandler;
import com.wub.struts.form.ClassSendForm;
import com.wub.struts.form.ClassSendListForm;



public class ClassSendAction extends DispatchAction {

	
	/**
	 * Bereitet das senden von Beurteilungen vor
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 */
	@SuppressWarnings("unchecked")
	public ActionForward prepareSendClass(ActionMapping mapping,
			ActionForm form, HttpServletRequest request,
			HttpServletResponse response) {
	
		/* Bevor eine einzelne Beurteilung gesendet werden kann, muss die "Gesamt-
		 * Beurteilung" gesendet worden sein
		 */
		// id aus request lesen
		int classId = Integer.parseInt(request.getParameter("classId"));
		
		ClassSendListForm listForm = AppraisalHandler.getInstance().getClassSendListForm(classId);
		
		// im request speichern
		request.getSession().setAttribute(AppraisalHandler.APPRAISALSENDFORM, listForm);
		
		return mapping.findForward("showSend");
	}
	
	
	
	/**
	 * Versendet Beurteilungen
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 */
	@SuppressWarnings("unchecked")
	public ActionForward sendClass(ActionMapping mapping,
			ActionForm form, HttpServletRequest request,
			HttpServletResponse response) {
		
		ClassSendListForm sendListForm = (ClassSendListForm)form;
		
		if (sendListForm != null) {
			// Form verarbeiten
			List sendFormList = sendListForm.getUserList();
			if (sendFormList != null) {
				int sendCount = 0;
				for (Object sendFrmObj : sendFormList) {
					ClassSendForm sendForm = (ClassSendForm)sendFrmObj;
					if (sendListForm.getSendToAll()) {
						// flag zur Sicherheit noch bei allen setzen
						sendForm.setSend(new Boolean(true));
					}
					if (sendForm.getSend() != null && sendForm.getSend()) {
						sendCount++;
					}
				}

				/* Versand nur starten, wenn überhaupt etwas zum Senden
				 * ausgewählt wurde
				 */
				if (sendCount > 0) {
					// Liste zur verarbeitung (zum Senden) weitergeben
					if (AppraisalHandler.getInstance().sendAppraisalMails(sendFormList)) {
						// Versenden erfolgreich
						return mapping.findForward("showSendSuccess");
					}
					else {
						// Senden fehlgeschlagen
						return mapping.findForward("showSendFailure");
					}
				}
			}
		}
		
		return mapping.findForward("showList");
	}
	
	
	
	
	/**
	 * Zeigt die Übersichtsliste an
	 * @param mapping
	 * @param form
	 * @return
	 */
	@SuppressWarnings("unchecked")
	public ActionForward showList(ActionMapping mapping,
			ActionForm form, HttpServletRequest request,
			HttpServletResponse response) {
		
		return mapping.findForward("showList");
		
	}
	
	
	
}