/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wub.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.wub.db.Users;
import com.wub.handlers.UserHandler;

/** 
 * MyEclipse Struts
 * Creation date: 02-18-2008
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class OpenUserLogonAction extends Action {

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		HttpSession session = request.getSession();
		
		// Wir prüfen ob der User bereits eingeloggt war
		if  (session != null) {
			Users userData = (Users)session.getAttribute(UserHandler.USERDATA);
			if (userData != null) {
				// user war bereits eingeloggt, direkt weiterleiten
				return mapping.findForward("relogin");
			}
		}
		
		
		// Standardmässig Logonpage anzeigen
		return mapping.findForward("showLogon");
		
	}
}