/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wub.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.wub.handlers.AdminUserHandler;

/** 
 * MyEclipse Struts
 * Creation date: 01-06-2008
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="open" path="pagen.adminmain"
 */
public class OpenAdminMainMenuAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		// Immer admin manager öffnen (wenn login ok)
		if(request.getSession().getAttribute(AdminUserHandler.ADMINDATA) == null) {
			return mapping.findForward("start");
		}
		else {
			return mapping.findForward("openAdminMain");
		}
		
	}
}