/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wub.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.wub.handlers.AdminUserHandler;
import com.wub.handlers.AppraisalHandler;
import com.wub.struts.form.AppraisalStatisticForm;
import com.wub.struts.form.StatisticSelectionForm;

/** 
 * MyEclipse Struts
 * Creation date: 02-24-2008
 * 
 * XDoclet definition:
 * @struts.action path="/statisticSelection" name="statisticSelectionForm" scope="request" validate="true"
 */
public class StatisticSelectionAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		
		HttpSession session = request.getSession();
		
		if(session != null && session.getAttribute(AdminUserHandler.ADMINDATA) != null) {
			StatisticSelectionForm statisticSelectionForm = (StatisticSelectionForm) form;
			
//			Integer subjectId = statisticSelectionForm.getClassId();
//			Integer teacherId = statisticSelectionForm.getTeacherId();
			Integer classId = statisticSelectionForm.getClassId();
			
			if (classId != null) {
				AppraisalStatisticForm statForm =
					AppraisalHandler.getInstance().getStatsPerClass(classId);
				
				if (statForm != null) {
					// Form im request speichern
					request.setAttribute(AppraisalHandler.APPRAISALSTATFORM, statForm);
					return mapping.findForward("showStatisticPerClass");
				}
			}
			
			// Statistik Startseite aufrufen (falls keine gültige Auswahl getroffen)
			return mapping.findForward("openStatistics");
			
//			if (subjectId != null) {
//				// Subject selektiert
//				
//			} else if (teacherId != null ) {
//				// Lehrer selektiert
//				
//			} else {
//				// Beurteilung selektiert
//				
//			}
		}
		
		// nicht eingeloggt -> zur Startseite leiten
		return mapping.findForward("start");
	}
}