/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wub.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.wub.handlers.AdminUserHandler;
import com.wub.handlers.AppraisalHandler;
import com.wub.struts.form.SubjectListForm;

/** 
 * MyEclipse Struts
 * Creation date: 01-10-2008
 * 
 * XDoclet definition:
 * @struts.action path="/subjectList" name="subjectListForm" input="/form/subjectList.jsp" scope="request" validate="true"
 */
public class SubjectListAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		SubjectListForm subjectListForm = (SubjectListForm) form;// TODO Auto-generated method stub

		if(request.getSession().getAttribute(AdminUserHandler.ADMINDATA) != null) {
			// Liste der Subjects vorbereiten
			if (subjectListForm == null) {
				subjectListForm = new SubjectListForm();
			}
			
			// abfüllen der List-Elemente
			AppraisalHandler appraisalHandler = AppraisalHandler.getInstance();
			List subjectList = appraisalHandler.getSubjectList();
		
			subjectListForm.setSubjectList(subjectList);
			
			// wir müssen die Liste im Scope speichern, damit sie auf der Seite verfügbar ist
			request.setAttribute(AppraisalHandler.SUBJECTLIST, subjectListForm);
			
			return mapping.findForward("showList");
		}
		
		// nicht eingeloggt -> zu startseite leiten
		return mapping.findForward("start");
		
		
	}
}