/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wub.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.wub.handlers.AdminUserHandler;
import com.wub.handlers.AppraisalHandler;
import com.wub.struts.form.TextElementListForm;

/** 
 * MyEclipse Struts
 * Creation date: 01-06-2008
 * 
 * XDoclet definition:
 * @struts.action path="/textElementList" name="textElementListForm" input="/form/textElementList.jsp" scope="request" validate="true"
 */
public class TextElementListAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		TextElementListForm textElementListForm = (TextElementListForm) form;
		
		
		if(request.getSession().getAttribute(AdminUserHandler.ADMINDATA) != null) {
			// Liste der Textelemente vorbereiten
			if (textElementListForm == null) {
				textElementListForm = new TextElementListForm();
			}
			
			// abfüllen der List-Elemente
			AppraisalHandler appraisalHandler = AppraisalHandler.getInstance();
			List textElementList = appraisalHandler.getTextElementList();
			
		
			textElementListForm.setTextElementList(textElementList);
			
			// wir müssen die Liste im Scope speichern, damit sie auf der Seite verfügbar ist
			request.setAttribute(AppraisalHandler.TEXTELEMENTLIST, textElementListForm);
			
			return mapping.findForward("showList");
		}
		
		// nicht eingeloggt -> zu startseite leiten
		return mapping.findForward("start");
		
	}
}