/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wub.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.wub.db.Users;
import com.wub.handlers.AppraisalHandler;
import com.wub.handlers.UserHandler;
import com.wub.struts.form.AppraisalForm;
import com.wub.struts.form.UserAppraisalInfoForm;

/** 
 * MyEclipse Struts
 * Creation date: 02-19-2008
 * 
 * XDoclet definition:
 * @struts.action path="/userPrepareAppraisal" name="userAppraisalListForm" scope="request" validate="true"
 */
public class UserPrepareAppraisalAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		HttpSession session = request.getSession();
		
		if (session != null) {
			Users userData = (Users)session.getAttribute(UserHandler.USERDATA);
			if (userData != null) {
				UserAppraisalInfoForm userAppraisalInfoForm = (UserAppraisalInfoForm) form;
				// User ist eingeloggt
				// -------------------
				// Die ausgewählte Beurteilung aufbauen/vorbereiten um dem User zu präsentieren
				if (userAppraisalInfoForm != null) {
					Integer statusId = userAppraisalInfoForm.getStatusId();
					if (statusId != null) {
						AppraisalForm appraisalForm = UserHandler.getInstance().getAppraisalFrom(statusId);
						
						// Formular speichern
						request.getSession().setAttribute(AppraisalHandler.APPRAISALFORM, appraisalForm);
						
						// auf die nächste Seite weiterleiten
						return mapping.findForward("showAppraisal");
					}
				}
			}
		}
		
		return mapping.findForward("startUser");
	}
}