/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wub.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.wub.db.Users;
import com.wub.handlers.UserHandler;
import com.wub.struts.form.AppraisalForm;
import com.wub.struts.form.AppraisalVoteElementForm;

/** 
 * MyEclipse Struts
 * Creation date: 02-19-2008
 * 
 * XDoclet definition:
 * @struts.action path="/userSaveAppraisal" name="appraisalForm" scope="request" validate="true"
 */
public class UserSaveAppraisalAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		HttpSession session = request.getSession();
		
		// nur Verarbeiten, wenn User eingeloggt
		if (session != null) {
			Users userData = (Users)session.getAttribute(UserHandler.USERDATA);
			if (userData != null) {
				// User ist eingeloggt
				AppraisalForm appraisalForm = (AppraisalForm) form;// TODO Auto-generated method stub
				
				Integer statusId = appraisalForm.getStatusId();
				List<AppraisalVoteElementForm> voteElementList = appraisalForm.getVoteElementList();
				
				// Abspeichern wenn Daten vorhanden
				if (statusId != null && voteElementList != null && voteElementList.size() > 0) {
					if (UserHandler.getInstance().saveAppraisal(statusId, voteElementList, userData.getUserId()))
					{
						// Speichern erfolgreich
						return mapping.findForward("showSuccess");
					}
					else
					{
						// Speichern fehlgeschlagen
						return mapping.findForward("showFailure");
					}
				}
			}
		}
		
		
		
		// Weiterleitung zur Startseite
		return mapping.findForward("startUser");
	}
}